### ISSUE TITLE
Tecnología a usar.

### ISSUE THREAD

**Issue by fnavarrogonzalez** [Gescosolution/Gesco#2]
Abro este issue para debatir la tecnología a usar. 
En la encuesta pasada estaba empatados NodeJS y PHP. 
La mayoría han programado en PHP sin embargo todos estabamos de acuerdo en aprender NodeJS.

Además casi todos estabamos de acuerdo creo en utilizar algun framework para minimizar el tiempo de desarrollo.

**Comment by germaaan** [comment]
A mi personalmente Node.js se me hace más amigable que PHP, la única "pega" es que es muy distinto a los lenguajes de programación más tradicionales, pero que vamos en línea con lo típico en lenguajes de scripting.

**Comment by fnavarrogonzalez** [comment]
Al final, tanto en PHP como NodeJS si vamos orientados a utilizar un framework hay que aprender. El caso es que no se hiciera cuesta arriba el proyecto junto con el resto de asignaturas. 
Por mi parte si nadie pone ninguna objeción pues utilizamos NodeJS + express/loopback

**Comment by germaaan** [comment]
Pues entonces propuesta oficial de NodeJS + express/loopback. Si para las 22 horas nadie ha dicho otra cosa lo tomamos como definitivo, que se nos echa el plazo de entrega encima.

**Comment by germaaan** [comment]
Decidido finalmente usar PHP + Symfony.
